# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/divbit/mnt/RingCT

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/divbit/mnt/RingCT

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/divbit/mnt/RingCT/CMakeFiles /home/divbit/mnt/RingCT/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/divbit/mnt/RingCT/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rct

# Build rule for target.
rct: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rct
.PHONY : rct

# fast build rule for target.
rct/fast:
	$(MAKE) -f CMakeFiles/rct.dir/build.make CMakeFiles/rct.dir/build
.PHONY : rct/fast

Test.o: Test.cpp.o

.PHONY : Test.o

# target to build an object file
Test.cpp.o:
	$(MAKE) -f CMakeFiles/rct.dir/build.make CMakeFiles/rct.dir/Test.cpp.o
.PHONY : Test.cpp.o

Test.i: Test.cpp.i

.PHONY : Test.i

# target to preprocess a source file
Test.cpp.i:
	$(MAKE) -f CMakeFiles/rct.dir/build.make CMakeFiles/rct.dir/Test.cpp.i
.PHONY : Test.cpp.i

Test.s: Test.cpp.s

.PHONY : Test.s

# target to generate assembly for a file
Test.cpp.s:
	$(MAKE) -f CMakeFiles/rct.dir/build.make CMakeFiles/rct.dir/Test.cpp.s
.PHONY : Test.cpp.s

crypto-ops-data.o: crypto-ops-data.cpp.o

.PHONY : crypto-ops-data.o

# target to build an object file
crypto-ops-data.cpp.o:
	$(MAKE) -f CMakeFiles/rct.dir/build.make CMakeFiles/rct.dir/crypto-ops-data.cpp.o
.PHONY : crypto-ops-data.cpp.o

crypto-ops-data.i: crypto-ops-data.cpp.i

.PHONY : crypto-ops-data.i

# target to preprocess a source file
crypto-ops-data.cpp.i:
	$(MAKE) -f CMakeFiles/rct.dir/build.make CMakeFiles/rct.dir/crypto-ops-data.cpp.i
.PHONY : crypto-ops-data.cpp.i

crypto-ops-data.s: crypto-ops-data.cpp.s

.PHONY : crypto-ops-data.s

# target to generate assembly for a file
crypto-ops-data.cpp.s:
	$(MAKE) -f CMakeFiles/rct.dir/build.make CMakeFiles/rct.dir/crypto-ops-data.cpp.s
.PHONY : crypto-ops-data.cpp.s

crypto-ops.o: crypto-ops.cpp.o

.PHONY : crypto-ops.o

# target to build an object file
crypto-ops.cpp.o:
	$(MAKE) -f CMakeFiles/rct.dir/build.make CMakeFiles/rct.dir/crypto-ops.cpp.o
.PHONY : crypto-ops.cpp.o

crypto-ops.i: crypto-ops.cpp.i

.PHONY : crypto-ops.i

# target to preprocess a source file
crypto-ops.cpp.i:
	$(MAKE) -f CMakeFiles/rct.dir/build.make CMakeFiles/rct.dir/crypto-ops.cpp.i
.PHONY : crypto-ops.cpp.i

crypto-ops.s: crypto-ops.cpp.s

.PHONY : crypto-ops.s

# target to generate assembly for a file
crypto-ops.cpp.s:
	$(MAKE) -f CMakeFiles/rct.dir/build.make CMakeFiles/rct.dir/crypto-ops.cpp.s
.PHONY : crypto-ops.cpp.s

crypto.o: crypto.cpp.o

.PHONY : crypto.o

# target to build an object file
crypto.cpp.o:
	$(MAKE) -f CMakeFiles/rct.dir/build.make CMakeFiles/rct.dir/crypto.cpp.o
.PHONY : crypto.cpp.o

crypto.i: crypto.cpp.i

.PHONY : crypto.i

# target to preprocess a source file
crypto.cpp.i:
	$(MAKE) -f CMakeFiles/rct.dir/build.make CMakeFiles/rct.dir/crypto.cpp.i
.PHONY : crypto.cpp.i

crypto.s: crypto.cpp.s

.PHONY : crypto.s

# target to generate assembly for a file
crypto.cpp.s:
	$(MAKE) -f CMakeFiles/rct.dir/build.make CMakeFiles/rct.dir/crypto.cpp.s
.PHONY : crypto.cpp.s

keccak.o: keccak.cpp.o

.PHONY : keccak.o

# target to build an object file
keccak.cpp.o:
	$(MAKE) -f CMakeFiles/rct.dir/build.make CMakeFiles/rct.dir/keccak.cpp.o
.PHONY : keccak.cpp.o

keccak.i: keccak.cpp.i

.PHONY : keccak.i

# target to preprocess a source file
keccak.cpp.i:
	$(MAKE) -f CMakeFiles/rct.dir/build.make CMakeFiles/rct.dir/keccak.cpp.i
.PHONY : keccak.cpp.i

keccak.s: keccak.cpp.s

.PHONY : keccak.s

# target to generate assembly for a file
keccak.cpp.s:
	$(MAKE) -f CMakeFiles/rct.dir/build.make CMakeFiles/rct.dir/keccak.cpp.s
.PHONY : keccak.cpp.s

keccak2.o: keccak2.cpp.o

.PHONY : keccak2.o

# target to build an object file
keccak2.cpp.o:
	$(MAKE) -f CMakeFiles/rct.dir/build.make CMakeFiles/rct.dir/keccak2.cpp.o
.PHONY : keccak2.cpp.o

keccak2.i: keccak2.cpp.i

.PHONY : keccak2.i

# target to preprocess a source file
keccak2.cpp.i:
	$(MAKE) -f CMakeFiles/rct.dir/build.make CMakeFiles/rct.dir/keccak2.cpp.i
.PHONY : keccak2.cpp.i

keccak2.s: keccak2.cpp.s

.PHONY : keccak2.s

# target to generate assembly for a file
keccak2.cpp.s:
	$(MAKE) -f CMakeFiles/rct.dir/build.make CMakeFiles/rct.dir/keccak2.cpp.s
.PHONY : keccak2.cpp.s

random.o: random.cpp.o

.PHONY : random.o

# target to build an object file
random.cpp.o:
	$(MAKE) -f CMakeFiles/rct.dir/build.make CMakeFiles/rct.dir/random.cpp.o
.PHONY : random.cpp.o

random.i: random.cpp.i

.PHONY : random.i

# target to preprocess a source file
random.cpp.i:
	$(MAKE) -f CMakeFiles/rct.dir/build.make CMakeFiles/rct.dir/random.cpp.i
.PHONY : random.cpp.i

random.s: random.cpp.s

.PHONY : random.s

# target to generate assembly for a file
random.cpp.s:
	$(MAKE) -f CMakeFiles/rct.dir/build.make CMakeFiles/rct.dir/random.cpp.s
.PHONY : random.cpp.s

rctOps.o: rctOps.cpp.o

.PHONY : rctOps.o

# target to build an object file
rctOps.cpp.o:
	$(MAKE) -f CMakeFiles/rct.dir/build.make CMakeFiles/rct.dir/rctOps.cpp.o
.PHONY : rctOps.cpp.o

rctOps.i: rctOps.cpp.i

.PHONY : rctOps.i

# target to preprocess a source file
rctOps.cpp.i:
	$(MAKE) -f CMakeFiles/rct.dir/build.make CMakeFiles/rct.dir/rctOps.cpp.i
.PHONY : rctOps.cpp.i

rctOps.s: rctOps.cpp.s

.PHONY : rctOps.s

# target to generate assembly for a file
rctOps.cpp.s:
	$(MAKE) -f CMakeFiles/rct.dir/build.make CMakeFiles/rct.dir/rctOps.cpp.s
.PHONY : rctOps.cpp.s

rctSigs.o: rctSigs.cpp.o

.PHONY : rctSigs.o

# target to build an object file
rctSigs.cpp.o:
	$(MAKE) -f CMakeFiles/rct.dir/build.make CMakeFiles/rct.dir/rctSigs.cpp.o
.PHONY : rctSigs.cpp.o

rctSigs.i: rctSigs.cpp.i

.PHONY : rctSigs.i

# target to preprocess a source file
rctSigs.cpp.i:
	$(MAKE) -f CMakeFiles/rct.dir/build.make CMakeFiles/rct.dir/rctSigs.cpp.i
.PHONY : rctSigs.cpp.i

rctSigs.s: rctSigs.cpp.s

.PHONY : rctSigs.s

# target to generate assembly for a file
rctSigs.cpp.s:
	$(MAKE) -f CMakeFiles/rct.dir/build.make CMakeFiles/rct.dir/rctSigs.cpp.s
.PHONY : rctSigs.cpp.s

rctTypes.o: rctTypes.cpp.o

.PHONY : rctTypes.o

# target to build an object file
rctTypes.cpp.o:
	$(MAKE) -f CMakeFiles/rct.dir/build.make CMakeFiles/rct.dir/rctTypes.cpp.o
.PHONY : rctTypes.cpp.o

rctTypes.i: rctTypes.cpp.i

.PHONY : rctTypes.i

# target to preprocess a source file
rctTypes.cpp.i:
	$(MAKE) -f CMakeFiles/rct.dir/build.make CMakeFiles/rct.dir/rctTypes.cpp.i
.PHONY : rctTypes.cpp.i

rctTypes.s: rctTypes.cpp.s

.PHONY : rctTypes.s

# target to generate assembly for a file
rctTypes.cpp.s:
	$(MAKE) -f CMakeFiles/rct.dir/build.make CMakeFiles/rct.dir/rctTypes.cpp.s
.PHONY : rctTypes.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... rct"
	@echo "... Test.o"
	@echo "... Test.i"
	@echo "... Test.s"
	@echo "... crypto-ops-data.o"
	@echo "... crypto-ops-data.i"
	@echo "... crypto-ops-data.s"
	@echo "... crypto-ops.o"
	@echo "... crypto-ops.i"
	@echo "... crypto-ops.s"
	@echo "... crypto.o"
	@echo "... crypto.i"
	@echo "... crypto.s"
	@echo "... keccak.o"
	@echo "... keccak.i"
	@echo "... keccak.s"
	@echo "... keccak2.o"
	@echo "... keccak2.i"
	@echo "... keccak2.s"
	@echo "... random.o"
	@echo "... random.i"
	@echo "... random.s"
	@echo "... rctOps.o"
	@echo "... rctOps.i"
	@echo "... rctOps.s"
	@echo "... rctSigs.o"
	@echo "... rctSigs.i"
	@echo "... rctSigs.s"
	@echo "... rctTypes.o"
	@echo "... rctTypes.i"
	@echo "... rctTypes.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

